name: GitHub Page Deploymet

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build_deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    # - run: npm test
    - run: git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
    - run: git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
    - run: npm run deploy
